### PR TITLE
Release v3.0.0

### PR DESCRIPTION
**Pull request by gadomski**
Includes a README note about this repo's relationship to **pystac**, as recommended by @thomas-maschler in https://github.com/stac-utils/stac-pydantic/pull/127#issuecomment-1821183694.

### CODE REVIEW

**Comment by jharrisonSV** [comment]
Hi. Do you know if v3.0.0 is going to be released soon?

**Comment by gadomski** [comment]
> Do you know if v3.0.0 is going to be released soon?

Thanks for the poke. I'll try to get to this tomorrow (Friday, 19 Jan). 🤹🏼

**Comment by vincentsarago** [comment]
@gadomski any blockers I could try to help you with? 🙏

**Comment by gadomski** [comment]
> @gadomski any blockers I could try to help you with? 🙏

Nothing other than my own distraction 🙃 . Thanks for the poke @vincentsarago.

**Comment by gadomski** [comment]
Actually @vincentsarago can you review and approve please and thank you?

**Comment by gadomski** [comment]
v3.0.0 is released:
- https://github.com/stac-utils/stac-pydantic/releases/tag/3.0.0
- https://pypi.org/project/stac-pydantic/3.0.0/

**Pull request merged**
