### PR TITLE
Check if datetime is a str instance before parsing

### PR DESCRIPTION
**Pull request by mzaglia**
Parse to rfc3339 only if the dates are strings.

### CODE REVIEW

**Comment by mzaglia** [comment]
can anyone take a look into this?

**Comment by kylebarron** [comment]
Not sure if this is superseded by https://github.com/stac-utils/stac-pydantic/pull/75. @geospatial-jeff might have a better idea

**Comment by geospatial-jeff** [comment]
Thanks @kylebarron you are correct, as of #75 the field is simply typed as datetime instead of a union.  When passed a string, pydantic will validate the date string against ISO format and convert to a datetime object.

**Comment by geospatial-jeff** [comment]
Apologies I'm trying to figure out GitHub mobile and it's not going so well haha.

I just realized that the ItemProperties.datetime member is still typed with a Union, once that is fixed I think we will have the behavior described in this PR.

**Comment by moradology** [comment]
Closing as superseded by #75

**Pull request closed without merging**
