### PR TITLE
Support collection list with top level links property

### PR DESCRIPTION
**Pull request by moradology**
The OGC standards seem to suggest that a top-level `links` property should be supported by the `/collections` endpoint. This PR adds a class to support this slightly more sophisticated list of collections. This change would be useful e.g. here: https://github.com/stac-utils/stac-fastapi/blob/master/stac_fastapi/api/stac_fastapi/api/app.py#L154

### CODE REVIEW

**Comment by lossyrob** [comment]
@moradology LGTM, can you run the pre-commit formatter on it so it passes CI?

**Review by geospatial-jeff — APPROVED** [review]
lgtm!

**Comment by moradology** [comment]
I believe one of you two will have to pull the trigger on this one as I lack write access to this repo.

Perhaps there's a better place for this question but, as the changes here will be useful for a slight modification to `stac-fastapi` which makes `Collection` list endpoint compliant with the STAC spec, how far off from the next release are we?

**Comment by moradology** [comment]
I think CI should succeed here. `black` has been run and test coverage is just north of 95%. Perhaps CI needs to be rerun but I think I lack the perms

**Comment by lossyrob** [comment]
@moradology CI was re-rerun...perhaps this is an issue with the version of black? `pydantic/stac-pydantic/stac_pydantic/api/__init__.py` is failing formatting. I also re-ran #90 CI and it failed on black as well. Something seems amiss with your local black matching CI's, maybe the version issue or it's not finding some local configuration

**Comment by moradology** [comment]
Agreed, I think there's something off with my version of black because it is not catching anything wrong. just a bunch of unchanged files locally: 
image


Investigating now...

**Comment by moradology** [comment]
@lossyrob Your guess about versions was on the money: `black==19.10b0` is an absolute must. I guess major version 20 is less picky

**Review by lossyrob — APPROVED** [review]

**Pull request merged**
